torta = input('Digite algo')
print (type(torta))
print (torta.isnumeric())
print (torta.isalnum())
print (torta.isalpha())
print (torta.isdecimal())
print (torta.isdigit())
print (torta.islower())
print (torta.isspace())
print (torta.isupper())
print (torta.istitle())
print (torta.isascii())
print (torta.isidentifier())
print (torta.isprintable())